export const DISCOUNT_LIST_REQUEST = "DISCOUNT_LIST_REQUEST";
export const DISCOUNT_LIST_SUCCESS = "DISCOUNT_LIST_SUCCESS";
export const DISCOUNT_LIST_FAIL = "DISCOUNT_LIST_FAIL";

export const DISCOUNT_DETAILS_REQUEST = "DISCOUNT_DETAILS_REQUEST";
export const DISCOUNT_DETAILS_SUCCESS = "DISCOUNT_DETAILS_SUCCESS";
export const DISCOUNT_DETAILS_FAIL = "DISCOUNT_DETAILS_FAIL";